"""
export_cfg_rows.py — regenerates CFG.rows (and CFG.totalNav) in js/data.js
from the already-cleaned Excel data (build_clean_records() in
psers_data_pipeline.py), not from the raw workbook directly. Follows the
same clean-records-in contract as the other exporters: never calls
load_included_rows() or psers_data_pipeline.ratios() on a single raw row —
only reads the already-computed clean record fields.

WHY THIS EXISTS (Round 73): CFG.rows is the dataset behind every
click-through popup/drawer in the deck (openPortfolioSummary, openHoldings,
openStrategy, openManager, openDataLens, fundDetail, the Manager
Concentration chart, etc. — see js/app.js). Before this round it was still
the 368-row, hand-carried-over-from-v6 dataset the README's "Data pipeline"
section always flagged as NOT YET migrated — so a popup's numbers (368
interests, $24.91bn NAV, 0.98x DPI...) could silently disagree with a
migrated slide showing the real 363-row Excel-derived numbers (363
positions, $24.8bn NAV, 0.97x DPI...) for the exact same portfolio. That
mismatch is what this exporter fixes: CFG.rows becomes the same 363
Include rows every migrated slide already uses, so every popup and every
page trace back to one dataset.

THIS IS UNLIKE THE OTHER THREE EXPORTERS in one structural way: it does
not write a standalone js/slide-data/*.data.js file. CFG.rows lives inside
js/data.js's single `const CFG = {...}` object, alongside CFG.titles
(hand-maintained deck order — never touched here). So render_js() doesn't
render a whole file; it renders just the `rows: [...]` array + `totalNav:`
value, and run() splices that between two sentinel comments already
present in js/data.js (`// === GENERATED BY tools/export_cfg_rows.py ...`
/ `// === END GENERATED ===`) rather than overwriting the file. Do not
remove those sentinels — they're how every future re-export finds the
right span without touching CFG.titles.

FIELD-BY-FIELD PROVENANCE (verified against the pre-migration 368-row
CFG.rows before writing this, not assumed):

- investment / portfolio / asset / manager / vehicle / tier1 / tier2 /
  tier3 / vintage / commitment / nav / dist / paid / total_value: direct
  passthrough from the clean record (reconstructed to raw dollars from the
  record's *_m millions fields — see _raw() below for why that's safe).
- dpi / rvpi / tvpi: passthrough from the clean record's own dpi/rvpi/tvpi
  — never recomputed here (Round 69's rule).
- unfunded / commitment_revised / unfunded_pct / funded_pct: passthrough
  from the clean record's unfunded_m/commitment_revised_m/unfunded_pct/
  funded_pct. unfunded_pct is Unfunded $ / Commitment $, capped at 100%,
  with a 0 fallback when commitment is 0. funded_pct is independent
  (paid / (paid + unfunded)).
- strategy: NOT the same field as the shared clean record's own `strategy`
  (that's the coarse Revised-Strategy-TANGIBLE-mapped label used by
  Strategy Mix/Portfolio Holdings/Key Considerations, e.g. "Real Estate &
  Infra"). CFG.rows' `strategy` is a different, finer 6-way legacy
  taxonomy (Buyout / Real Estate / Credit / Infrastructure / Growth &
  Venture / Special Situations) that every popup/drawer/dropdown in
  js/app.js filters by (openStrategy, openMarketTable, managerDataset,
  constrainedFilter, Strategy Mix's own STRATEGY_META.strategyKey — see
  export_strategy_mix.py) and that ISN'T literally a column in the
  workbook anywhere (checked Clean Data, Raw Data, and Summary — none of
  the three has a "Buyout"/"Credit"/"Special Situations" taxonomy column).
  Reverse-engineered from the pre-migration data: crosstabbed every row's
  tier1 (Asset Class Tier 1) against its legacy `strategy` value and found
  a clean, unambiguous 1:1 mapping with zero exceptions across all 368
  rows — see TIER1_TO_LEGACY_STRATEGY below. Raises on an unmapped tier1
  value rather than guessing, same pattern as STRATEGY_DISPLAY_LABELS in
  the core module.
- strategy2: confirmed via a full-project grep that NOTHING reads this
  field anywhere in js/app.js or js/pages/*.js — it's dead data. Its
  pre-migration values (e.g. "Distressed Debt" for a row whose `strategy`
  was "Credit") don't map cleanly onto any single workbook column either
  (tier2 comes close but doesn't match verbatim). Rather than invent a
  value for a field nothing reads, this migration sets strategy2 = strategy
  — a documented simplification, not a guess at a "real" value, since
  there's no real value to reproduce and no code path that would notice.
- vintage_segment: matches export_strategy_mix.py's _vintage_segment()
  exactly (same cut points, confirmed against CFG.rows' own pre-migration
  min/max vintage per segment) — duplicated here rather than imported,
  same "two independent derived groupings" reasoning
  export_key_considerations.py already documents for why it doesn't import
  from export_strategy_mix.py either.
- unfunded_segment / dpi_segment / tvpi_segment / nav_segment: confirmed
  via a full-project grep that NOTHING reads any of these three fields —
  dead data, like strategy2. Reproduced anyway (not dropped) since the
  thresholds were cleanly, unambiguously reverse-engineered with zero
  exceptions across all 368 pre-migration rows (see the _*_segment()
  functions below) and dropping documented schema fields that a future
  feature might read is a bigger risk than keeping them accurate.

Run this any time source-data/PSERS_Total Private Market Portfolio_Final.xlsx
changes (or just run tools/export.py, which calls this automatically):

    python3 tools/export_cfg_rows.py
"""

import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from psers_data_pipeline import load_included_rows, build_clean_records

DATA_JS_PATH = os.path.join(os.path.dirname(__file__), "..", "js", "data.js")

GENERATED_START = "  // === GENERATED BY tools/export_cfg_rows.py — DO NOT HAND-EDIT BELOW ==="
GENERATED_END = "  // === END GENERATED (tools/export_cfg_rows.py) ==="
TOTAL_NAV_PREFIX = "  totalNav: "

# tier1 (Asset Class Tier 1 (Investment)) -> CFG.rows' legacy `strategy`
# value. See module docstring for how this was reverse-engineered (a clean
# 1:1 crosstab against all 368 pre-migration rows, zero exceptions). Raises
# on an unmapped tier1 rather than guessing -- same pattern as
# STRATEGY_DISPLAY_LABELS in psers_data_pipeline.py.
TIER1_TO_LEGACY_STRATEGY = {
    "Infrastructure Partnership": "Infrastructure",
    "Infrastructure Co-Investment": "Infrastructure",
    "Private Credit Partnership": "Credit",
    "Private Credit Co-Investment": "Credit",
    "Venture Capital": "Growth & Venture",
    "Growth Equity": "Growth & Venture",
    "Buyout": "Buyout",
    "PE Special Situations": "Special Situations",
    "Real Estate Partnership": "Real Estate",
    "Direct Real Estate": "Real Estate",
    "Real Estate Co-Investment": "Real Estate",
}


def _legacy_strategy(record):
    tier1 = record["tier1"]
    if tier1 not in TIER1_TO_LEGACY_STRATEGY:
        raise RuntimeError(
            f"Unmapped Asset Class Tier 1 value {tier1!r} on "
            f"{record['investment']!r} — add it to TIER1_TO_LEGACY_STRATEGY "
            f"in export_cfg_rows.py (don't guess a legacy strategy label)."
        )
    return TIER1_TO_LEGACY_STRATEGY[tier1]


def _slide_strategy(record):
    """Column E "Strategy for Fund Level Metrics", with VC & Growth mapped
    to Growth & Venture. Same 5-way bucket as Strategy Mix."""
    return record["strategy_fund"]


def _vintage_segment(vintage):
    """Same cut points as export_strategy_mix.py's _vintage_segment() —
    see that file's module docstring and this file's own docstring above
    for why duplicated, not imported."""
    v = int(vintage)
    if v <= 2012:
        return "Pre-2013"
    if v <= 2015:
        return "2013-2015"
    if v <= 2018:
        return "2016-2018"
    if v <= 2021:
        return "2019-2021"
    return "2022+"


def _unfunded_segment(unfunded_pct):
    """Thresholds reverse-engineered from all 368 pre-migration CFG.rows
    rows (0 exceptions) — see module docstring. Dead data (see docstring)."""
    if unfunded_pct < 0.15:
        return "Under 15%"
    if unfunded_pct < 0.30:
        return "15%-30%"
    return "Over 30%"


def _dpi_segment(dpi):
    """Thresholds reverse-engineered from all 368 pre-migration CFG.rows
    rows (0 exceptions). Dead data (see docstring) -- NOT the same
    computation as the Manager Concentration chart's own 3-bucket split,
    which is computed live from per-manager aggregate DPI, not per-row."""
    if dpi < 0.25:
        return "Under 0.25x"
    if dpi <= 0.75:
        return "0.25x-0.75x"
    return "Over 0.75x"


def _tvpi_segment(tvpi):
    """Thresholds reverse-engineered from all 368 pre-migration CFG.rows
    rows (0 exceptions). Dead data (see docstring)."""
    if tvpi < 1.2:
        return "Under 1.2x"
    if tvpi <= 1.7:
        return "1.2x-1.7x"
    return "Over 1.7x"


def _nav_segment(nav_m):
    """Thresholds reverse-engineered from all 368 pre-migration CFG.rows
    rows (0 exceptions); nav_m is in millions. Dead data (see docstring)."""
    if nav_m < 10:
        return "Under $10M"
    if nav_m < 50:
        return "$10M-$50M"
    if nav_m < 150:
        return "$50M-$150M"
    return "Over $150M"


def _raw(millions_value):
    """Reconstruct a raw-dollar figure from an already-computed *_m
    (millions, 6dp-rounded) field rather than threading a second, raw-
    dollar-precision field through build_clean_records() for this one
    exporter. This loses sub-$1 precision (6dp of millions = $1) that the
    pre-migration CFG.rows had (down to cents) -- deliberately: every
    place these numbers reach the screen (fmtMoney() in js/app.js) rounds
    to whole dollars below $1M and to 1-2dp of millions/billions above
    it, so a sub-$1 difference is provably never visible in any rendered
    popup, table, or chart. Rounded to cents here anyway (not left as a
    raw float) purely so the generated file's numbers look like the
    dollar figures they are, not floating-point noise.
    """
    return round(millions_value * 1e6, 2)


def build_rows(records):
    rows = []
    for r in records:
        rows.append({
            "investment": r["investment"],
            "portfolio": r["portfolio"],
            "asset": r["asset"],
            "manager": r["manager"],
            "vehicle": r["vehicle"],
            "vintage": int(r["vintage"]),
            "strategy": _legacy_strategy(r),
            "strategy2": _legacy_strategy(r),  # see docstring: dead field, no real value to reproduce
            "slideStrategy": _slide_strategy(r),
            "tier1": r["tier1"],
            "tier2": r["tier2"],
            "tier3": r["tier3"],
            "commitment": _raw(r["commitment_m"]),
            "nav": _raw(r["nav_m"]),
            "dist": _raw(r["distributions_m"]),
            "paid": _raw(r["paid_in_m"]),
            "unfunded": _raw(r["unfunded_m"]),
            "commitment_revised": _raw(r["commitment_revised_m"]),
            "total_value": _raw(r["total_value_m"]),
            "funded_pct": r["funded_pct"],
            "unfunded_pct": r["unfunded_pct"],
            "dpi": r["dpi"],
            "rvpi": r["rvpi"],
            "tvpi": r["tvpi"],
            "vintage_segment": _vintage_segment(r["vintage"]),
            "unfunded_segment": _unfunded_segment(r["unfunded_pct"]),
            "dpi_segment": _dpi_segment(r["dpi"]),
            "tvpi_segment": _tvpi_segment(r["tvpi"]),
            "nav_segment": _nav_segment(r["nav_m"]),
        })
    total_nav = round(sum(r["nav"] for r in rows), 6)
    return {"rows": rows, "totalNav": total_nav}


def _json_string(s):
    return str(s).replace("\\", "\\\\").replace('"', '\\"')


def render_rows_block(rows):
    lines = [GENERATED_START]
    lines.append(
        "  // (see js/data.js's header comment and README.md's \"Data pipeline\""
    )
    lines.append(
        "  // section for how CFG.rows is produced; re-run tools/export.py after"
    )
    lines.append(
        "  // editing the source workbook rather than editing this array by hand)"
    )
    lines.append("  rows: [")
    for row in rows:
        fields = []
        for key in (
            "investment", "portfolio", "asset", "manager", "vehicle",
        ):
            fields.append(f'"{key}":"{_json_string(row[key])}"')
        fields.append(f'"vintage":{row["vintage"]}')
        for key in ("strategy", "strategy2", "slideStrategy", "tier1", "tier2", "tier3"):
            fields.append(f'"{key}":"{_json_string(row[key])}"')
        for key in (
            "commitment", "nav", "dist", "paid", "unfunded",
            "commitment_revised", "total_value", "funded_pct",
            "unfunded_pct", "dpi", "rvpi", "tvpi",
        ):
            fields.append(f'"{key}":{row[key]}')
        for key in (
            "vintage_segment", "unfunded_segment", "dpi_segment",
            "tvpi_segment", "nav_segment",
        ):
            fields.append(f'"{key}":"{_json_string(row[key])}"')
        lines.append("  {" + ",".join(fields) + "},")
    lines.append("  ],")
    lines.append(GENERATED_END)
    return "\n".join(lines)


def run(clean_records=None):
    if clean_records is None:
        clean_records = build_clean_records(load_included_rows())
    data = build_rows(clean_records)

    data_js_path = os.path.normpath(DATA_JS_PATH)
    with open(data_js_path, "r", encoding="utf-8") as f:
        content = f.read()

    if GENERATED_START not in content or GENERATED_END not in content:
        raise RuntimeError(
            f"{data_js_path} is missing the GENERATED sentinel comments "
            f"export_cfg_rows.py needs to locate CFG.rows -- see this "
            f"script's module docstring. Add them once by hand around the "
            f"existing rows:[...] array before re-running this."
        )

    start_idx = content.index(GENERATED_START)
    end_idx = content.index(GENERATED_END) + len(GENERATED_END)
    new_block = render_rows_block(data["rows"])
    content = content[:start_idx] + new_block + content[end_idx:]

    if TOTAL_NAV_PREFIX not in content:
        raise RuntimeError(f"{data_js_path} is missing a '{TOTAL_NAV_PREFIX}' line.")
    tn_start = content.index(TOTAL_NAV_PREFIX)
    tn_end = content.index("\n", tn_start)
    content = content[:tn_start] + f"{TOTAL_NAV_PREFIX}{data['totalNav']}," + content[tn_end:]

    with open(data_js_path, "w", encoding="utf-8") as f:
        f.write(content)

    return {
        "slide": "CFG.rows (legacy popups/drawers dataset)",
        "output": data_js_path,
        "count": len(data["rows"]),
        "totalNav": data["totalNav"],
    }


def main():
    result = run()
    print(f"Wrote {result['output']}")
    print(f"Rows: {result['count']} | totalNav: {result['totalNav']}")


if __name__ == "__main__":
    main()
